spring:
  application:
    name: API-GATEWAY
  server:
    port: 8080
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
