version: '3'

services:
  # MySQL Database
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: demo_1
#      MYSQL_USER: root
      MYSQL_PASSWORD: admin_password
    ports:
      - "3306:3306" # Expose MySQL port
    networks:
      - my_network

  # Spring Boot Application
#  spring-app:
#    image: your-spring-boot-image:latest
#    container_name: spring-app-container
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo_1?useSSL=false
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin_password
#    depends_on:
#      - mysql
#    ports:
#      - "8080:8080" # Expose Spring Boot app port
#    networks:
#      - my_network

networks:
  my_network:
